apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-deployment
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: skaffold
  template:
    metadata:
      name: skaffold-pod
      labels:
        app: skaffold
    spec:
      containers:
      - name: skaffold-app
        image: glgl2131/hello
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: skaffold-svc
spec:
  selector:
    app: skaffold
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
